name: stage

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      - id: 'deploy'
        name: Deploy Staging
        uses: 'google-github-actions/deploy-appengine@v0'
        with:
          version: ${{ steps.vars.outputs.sha_short }}
          promote: false
      - id: 'test'
        run: |
          curl "${{ steps.deploy.outputs.url }}" | grep '"mins": 5'
      - name: Promote
        id: 'promote'
        uses: 'google-github-actions/deploy-appengine@v0'
        with:
          version: ${{ steps.vars.outputs.sha_short }}
          promote: true
      - id: outputUrl
        run: 'echo "${{ steps.promote.outputs.url }}"'

